name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          # See version matrix @ https://typo3.org/cms/roadmap
          - { php: 8.2, typo3: 12.4 }
          - { php: 8.3, typo3: 13.2 }

    env: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install composer dependencies
        run: |
          composer req typo3/cms-core:^${{ matrix.env.typo3 }} -W

      - name: Run PHPStan
        run: composer phpstan

      - name: Warmup typo3 cache
        run: composer exec typo3 -- cache:warmup